# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18bAWhvETnkj925uffkPlEDSEAEeYycAx
"""

import random

def StartGame():
    words = ['make', 'could', 'should', 'might']
    correct_word = random.choice(words)
    guesses_left = 10
    guessed_letters = []
    word_display = ['_'] * len(correct_word)

    print(f'------------You have {guesses_left} guesses. Select carefully!------------')
    print('----------------------------------------------------------')
    print('------------------Select a letter!-------------------------')

    while guesses_left > 0:
        print("\nCurrent word: " + " ".join(word_display))
        print(f"Guessed letters: {', '.join(guessed_letters)}")
        print(f"You have {guesses_left} guesses left.")

        selected_letter = input("Enter a letter: ").lower()

        if len(selected_letter) != 1 or not selected_letter.isalpha():
            print("---------------Please select a single letter!------------------")
            continue

        if selected_letter in guessed_letters:
            print(f"You've already guessed '{selected_letter}'. Try another letter.")
            continue

        guessed_letters.append(selected_letter)

        if selected_letter in correct_word:
          guesses_left -= 1
          print(f"Good guess! The letter '{selected_letter}' is in the word.")
          for i in range(len(correct_word)):
            if correct_word[i] == selected_letter:
              word_display[i] = selected_letter

        else:
          guesses_left -= 1
          print(f"Oops! The letter '{selected_letter}' is not in the word.")

        if "_" not in word_display:
            print(f"\nCongratulations! You've guessed the word: {correct_word}")
            break

    if guesses_left == 0:
        print(f"\nSorry, you're out of guesses. The correct word was: {correct_word}")

def main():
    print('----------------------------------------------------------')
    print('------------Welcome To Text-Based Hangman Game------------')
    print('----------------------------------------------------------')
    StartGame()


main()